#SVM Theory
Ch9 Intro to Statistical Learning 

SUPPORT VECTOR MACHINES (SVMs) are SUPERVISED LEARNING  models with associated learning algorithms that analyze data and recognize patterns used for CLASSIFICATION and REGRESSION ANALYSIS.

#IN THIS LECTURE WE WILL TALK ABOUT THEM FOR CLASSIFICATION ANALYSIS

#Given a set of TRAINING example, each marked for belonging to one of two catergories(BINARY), an SVM training algorithm builds a model that assigns new examples(or TEST DATA Pts) into one category or the other, making it a non probabilitist binary linear classifier.

#An SVM model is s representation of the examples as points in space, mapped so that he exampels of the separate categories are divided by a clear gap that is as wide as possible. 

#New examples are then mapped into that same space and predicted to belong to a category based on which side of the gap they fall on

#HYPERPLANE- this is the LINE that separates the Classes, however we can have many options of where this line is drawn. 
#How do you choose line that separtates classes best?
#What we would like to do is choose a HYPERPLANE that maximizes the margin BETWEEN the CLASSES
#The VECTOR POINTS that the margin touch are SUPPORT VECTORS which is where name SVM comes from

#We can expland this idea to NON LINEARLY separble data thru the KERNAL TRICK 
#NON LINEAR data is basically circular data inside another circle
#Thru KERNAL TRICK we end up viewing this data in a HIGHER DIMENSION. In this case we look at a 3rd - Z LABEL AXIS

In [1]:
#Support Vector Machines with Python
#We will start our Example by using SVMs on 
#BreastCancer data to predict whether a tumer is 
#malignant or benign 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#We'll use the built in breast cancer dataset from 
#Scikit Learn. We can get with the load function:
from sklearn.datasets import load_breast_cancer
df = load_breast_cancer()

In [3]:
#The data set is presented in a DICTIONARY form:
df.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [14]:
df['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [15]:
#So this is what the TARGET references
df['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [4]:
#If you want a detailed Deription of Dataset
print(df['DESCR'])
#so we have 569 instances with 30 numeric, ATTRIBUTES
#WE WILL:
 #PREDICT whether a tumer is MALIGNET or BENIGN 

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [13]:
#Now we will set up new DF using the KEYS to grab the
 #data
df2=pd.DataFrame(df['data'],columns=df['feature_names'])
df2.head(2)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
mean radius                569 non-null float64
mean texture               569 non-null float64
mean perimeter             569 non-null float64
mean area                  569 non-null float64
mean smoothness            569 non-null float64
mean compactness           569 non-null float64
mean concavity             569 non-null float64
mean concave points        569 non-null float64
mean symmetry              569 non-null float64
mean fractal dimension     569 non-null float64
radius error               569 non-null float64
texture error              569 non-null float64
perimeter error            569 non-null float64
area error                 569 non-null float64
smoothness error           569 non-null float64
compactness error          569 non-null float64
concavity error            569 non-null float64
concave points error       569 non-null float64
symmetry error             569 

In [14]:
df2.shape

(569, 30)

In [ ]:
#Lets do some EXPLORATORY Anlysis
#it is encouraged we do Visual anaysis with Seaborn
# or MPL but there so many different feautures and 
# unless you are an expert in Cancer its jsut hard to 
# interpret

#We will go strait into the model

In [3]:
#Side  stuff
df['target'].shape

(569,)

In [11]:
ytry = pd.DataFrame(df['target'])
ytry

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [12]:
ytry.shape

(569, 1)

In [22]:
ytry.values.reshape(-1,).shape

(569,)

In [17]:
#TRAIN/TEST Split
from sklearn.model_selection import train_test_split
#FEAUTURES
X = df2
#TARGET is ARRAY OF ZEROS and ONES
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [18]:
#TRAIN the SUPPORT VECTOR CLASSIFIER 
from sklearn.svm import SVC
#Create an Instance of SVC model
model = SVC()
#FIT MODEL to TRAINING data
model.fit(X_train,y_train)
#We have quite a few params such as GAMMA, C, DEGREE, 
#KERNAL, ect. We are going to be looking at these later
#on 

/Users/thomascoenen/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [19]:
#PREDICTIONS and EVALUATION
#PREDICT using Default values (X_TEST)
predictions = model.predict(X_test)
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
#CLASSIFICAITON RPT and CONFUSION MATRIX
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))
#We see something very interesting occur. So this 
# MODEL with the default values predicted that no tumors
# were in the ZERO class. And we get a warning that PREC 
# and FSCORE are ill defined and being set to 0 in 
# labels with no predicted samples. You see that in 
# ConFusion MATRIX as well. 

#It basically predicted everything belonged to CLASS1.
# The reason for this is bc our model needs to have its
# parameters adjusted. It may also help to normalize the
# data as well when you are passing it into a SVM. We 
# can search for the BEST PARAMS using a GRID SEARCH.  

[[  0  66]
 [  0 105]]


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        66
           1       0.61      1.00      0.76       105

    accuracy                           0.61       171
   macro avg       0.31      0.50      0.38       171
weighted avg       0.38      0.61      0.47       171



/Users/thomascoenen/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


#A GRID SEARCH allows you to find the right params such as what C or GAMMA VALUES to use. FInding those right params is usually tricky but luckily we can be lazy and try a bunch of combinations and see what works best. This idea of creating a GRID of parameters is trying out all the best combinations is called a GRID SEARCH

In [22]:
#GRID SEARCH
from sklearn.model_selection import GridSearchCV
#GRID SEARCH CV takes in a DICTIONARY that describes 
#the parameters that should be TRIED and a MODEL to 
#TRAIN. The GRID PARAMS are defined as a DICT where the 
#KEYS=PARAMS, and VALUES=LIST of SETTINGS to be TESTED

#The KEYS are going to be a DICT where the KEYS are 
#the actual params that go into the MODEL you are using.
#In this case we are using an SVC as our MODEL and we 
#see various params available to us above (where we 
#did: model.fit(X_train,y_train)) 

#As an OVERALL GENERALIZATION we can say that 'C' 
controls the cost of MISCLASSIFICATION on the TRAINING
DATA. a LARGE 'C' calue gives you LOW BIAS and HIGH 
VARIANCE. LOW BIAS bc you penalize the cost of 
MISCLASSIFICATION a lot with a larger 'C'value. With a
smaller 'C' value you wont penalize that cost as much 
so it gives you a HIGHER BIAS and LOWER VARIANCE. That 
has to do with the BIAS VARIANCE Trade off.

The GAMMA Parameter has to do with the FREE Parameter 
of the GAUSSIEN Radial bases function, and thats what 
the KERNAL is(RADIAL BASES FUNCTION - its the default 
KERNAL and probly the best one to use by 
DEFAULT which is why its the default). 
This GAMMA param is that free parameter in that RADIAL 
BASES function. Basically a SMALL GAMMA means a 
GAUSSIEN with a LARGE VARIANCE. and a LARGE GAMMA 
value is going to lead to a HIGH BIAS and LOW VARIANCE
in the model or vice vera. So if GAMMA is LARGE, 
VARIANCE is SMALL implying that SUPPORT VECTOR does 
not have a WIDE SPREAD influence. 

Reading in recommendated in Ch9 Intro to Statistical 
Learning for Math behing SUpport Vector Machines. For 
more practical use case just think of C and GAMMA 
values as params you can ADJUST with a GRID SEARCH

In [23]:
#CREATE GRID
#DO GRID SEARCH with PARAM_GRID TO FIND BEST 
  #PARAMETERS
    
#We will test 'C' from stated values in list
param_grid = {'C':[0.1,1,10,100,1000], 'gamma':[1,0.1,0.01,0.001,0.0001]}
#Feed PARAM GRID to GRID SEARCH CV

#INSTACIATE a GRID OBJECT from GRID SEARCH CV
#GSCV will take ESTIMATOR and PARAMGRID, and theres
#a refit Param and VERBOSE Argument as well
#One great thing about GSCV is that it is essential a 
#META estimator. It takes an estimator just like we did 
#with SVC and creates a NEW ESTIMATOR that behaves 
#exactly the same, in this case just like a classifier.
#You can choose VERBOSE to be whatever you want, the 
#HIGHER the number the more VERBOSE, which means the 
#TEXT OUTPUT of the desicption of the process. Recommend 
#you put some number as verbose(the defualt is 0), 
#otherwise you wont know if model is doing something
#bc GRID SEARCHES TAKE A LONG TIME especially if you 
#have a ton of params to check. 
#REFIT=TRUE (default but we will put it anyway) 

#Run GRID SEARCH
grid = GridSearchCV(SVC(),param_grid,verbose=3)

In [24]:
#FIT the GRID to TRAINING data
grid.fit(X_train,y_train)
#We see since its VERBOSE it outputed these values
#for us

#What FIT does its a bit more involved than usual. 
# First its going to run the same loop with CROSS 
# VALIDATION to find the best parameter combination. 
# Once it has the best combination, it runs FIT again 
# on all data past to that FIT WITHOUT CROSS VALIDATION 
# to build a single NEW MODEL using the best parameter 
# setting. You can GRAB the best param setting STRAIT 
# off of the GRID OBJECT

/Users/thomascoenen/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.632, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.632, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ...................... C=0.1, gamma=1, score=0.636, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.632, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.632, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] .................... C=0.1, gamma=0.1, score=0.636, total=   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ...........

[CV] ................. C=100, gamma=0.0001, score=0.917, total=   0.0s
[CV] C=100, gamma=0.0001 .............................................
[CV] ................. C=100, gamma=0.0001, score=0.977, total=   0.0s
[CV] C=100, gamma=0.0001 .............................................
[CV] ................. C=100, gamma=0.0001, score=0.939, total=   0.0s
[CV] C=1000, gamma=1 .................................................
[CV] ..................... C=1000, gamma=1, score=0.632, total=   0.0s
[CV] C=1000, gamma=1 .................................................
[CV] ..................... C=1000, gamma=1, score=0.632, total=   0.0s
[CV] C=1000, gamma=1 .................................................
[CV] ..................... C=1000, gamma=1, score=0.636, total=   0.0s
[CV] C=1000, gamma=0.1 ...............................................
[CV] ................... C=1000, gamma=0.1, score=0.632, total=   0.0s
[CV] C=1000, gamma=0.1 ...............................................
[CV] .

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:    0.8s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [25]:
#Grab BEST PARAMS setting of the GRID OBJECT
grid.best_params_
#Returns Combination of parameters that had BEST 
 #CROSS VALIDATION SCORE

{'C': 10, 'gamma': 0.0001}

In [26]:
#You can also grab BEST ESTIMATOR and BEST SCORE
grid.best_estimator_

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [28]:
#RERUN our PREDICTIONS on this GRID OBJECT just like a 
 #normal model
grid_predictions = grid.predict(X_test)
grid_predictions

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1])

In [29]:
#CLASSIFICAITON RPT and CONFUSION MATRIX
print(confusion_matrix(y_test,grid_predictions))
print('\n')
print(classification_report(y_test,grid_predictions))
#Model much better now. In fact it's 95% accurate. 
#so an SVM we are going to have to have to do a GRID 
# SEARCH. No real way to have a good intuitive to know 
# what a good 'C' value and good GAMMA value. What you 
# should be aware of is GRID SEARCHES can take a long 
# time if you have a large dataset. In real life you 
# will set everything up and make sure Data is clean 
# and do a Grid Search on a small set of grids, just 1 
# or 2, and make sure that works correctly, adn once it 
# does, youll set ur full param grid with as many 
# default values that you want in your LIST. Run GRID 
# SEARCH and take a break while Grid Search is running. 

[[ 60   6]
 [  3 102]]


              precision    recall  f1-score   support

           0       0.95      0.91      0.93        66
           1       0.94      0.97      0.96       105

    accuracy                           0.95       171
   macro avg       0.95      0.94      0.94       171
weighted avg       0.95      0.95      0.95       171

